- block:
    - name: stop fuseki service
      ansible.builtin.systemd:
        name: container-fuseki
        state: stopped

    - name: copy configuration file
      ansible.builtin.copy:
        src: prez.ttl
        dest: /fuseki/configuration/prez.ttl
        owner: "{{ vault.server.user }}"
        mode: "0644"

    - name: start fuseki service
      ansible.builtin.systemd:
        name: container-fuseki
        state: restarted

  become: true
